"""
================================================================================
 RAW DATA GENERATION / MOCK INGESTION SOURCE
================================================================================
Purpose:
    This script programmatically sets up the raw, unstructured text files that 
    will serve as the foundational external knowledge base for our RAG pipeline.

What it does:
    1. Creates a local 'data/' directory if it doesn't already exist.
    2. Writes distinct, domain-specific articles detailing core AI and RAG 
       concepts (e.g., Chunking, Embeddings, Evaluation, Agents, Multi-Modal).
    3. Serves as the starting point for simulating document ingestion workflows.

Usage:
    Run this file first to populate your sandbox environment with source files.
================================================================================
"""

import os
import sys

def create_sample_documents(data_dir: str):
    """Creates a local directory and writes sample text files into it."""
    sample_docs_content = [
        """
        Machine Learning Fundamentals
        
        Machine learning is a subset of artificial intelligence that enables systems to learn 
        and improve from experience without being explicitly programmed. There are three main 
        types of machine learning: supervised learning, unsupervised learning, and reinforcement 
        learning. Supervised learning uses labeled data to train models, while unsupervised 
        learning finds patterns in unlabeled data. Reinforcement learning learns through 
        interaction with an environment using rewards and penalties.
        """,
        
        """
        Deep Learning and Neural Networks
        
        Deep learning is a subset of machine learning based on artificial neural networks. 
        These networks are inspired by the human brain and consist of layers of interconnected 
        nodes. Deep learning has revolutionized fields like computer vision, natural language 
        processing, and speech recognition. Convolutional Neural Networks (CNNs) are particularly 
        effective for image processing, while Recurrent Neural Networks (RNNs) and Transformers 
        excel at sequential data processing.
        """,
        
        """
        Natural Language Processing (NLP)
        
        NLP is a field of AI that focuses on the interaction between computers and human language. 
        Key tasks in NLP include text classification, named entity recognition, sentiment analysis, 
        machine translation, and question answering. Modern NLP heavily relies on transformer 
        architectures like BERT, GPT, and T5. These models use attention mechanisms to understand 
        context and relationships between words in text.
        """,

        """
        Vector Embeddings and Vector Databases

        Vector embeddings are numerical representations of data, such as text, images, or audio, captured in a high-dimensional continuous vector space. These dense vectors are generated by deep learning models to capture the semantic and contextual meaning of words or phrases rather than just their literal characters.
        In an embedding space, words with similar meanings or contexts are mathematically positioned closer to one another, allowing computers to compute contextual similarity.
        Vector databases are specialized storage engines designed specifically to index, store, and rapidly query high-dimensional vectors. Traditional relational databases struggle with vector data because standard indexing methods cannot scale to high dimensions.
        Vector databases utilize advanced indexing algorithms like Hierarchical Navigable Small World (HNSW) or Inverted File Index (IVF) to perform Approximate Nearest Neighbor (ANN) searches, allowing systems to look through millions of vectors in milliseconds.
        """,
        
        """
        Retrieval-Augmented Generation (RAG) Architecture

        Retrieval-Augmented Generation (RAG) is a design pattern that optimizes the output of a Large Language Model (LLM) by referencing an authoritative, external knowledge base before generating a response. Standard LLMs suffer from static training data, temporal cutoffs, and a tendency to hallucinate facts when they lack information.
        RAG solves this by decoupling the model's parametric memory (what it learned during training) from its non-parametric memory (the external vector store).
        The standard RAG pipeline operates in three distinct phases: ingestion, retrieval, and generation. During ingestion, source documents are broken into chunks, embedded into vectors, and stored in a vector database.
        When a user submits a query, the retrieval system converts the query into an embedding, searches the vector store for the most contextually relevant chunks, and pulls them. Finally, during generation, the retrieved chunks are stuffed into the prompt alongside the user's original question, giving the LLM the exact context it needs to write an accurate, grounded answer.
        """,
        
        """
        Large Language Models (LLMs) and Fine-Tuning

        Large Language Models (LLMs) are massive deep learning models trained on trillions of tokens of text data to predict the next word in a sequence. Built predominantly on the Transformer architecture, these models use billions of parameters to learn the syntax, semantics, and nuances of human language.
        While foundational models exhibit impressive general capabilities, they often require domain-specific adaptation to perform specialized tasks accurately.
        Fine-tuning is the process of taking a pre-trained foundational model and training it further on a smaller, targeted dataset to adapt it to a specific task or industry. Full parameter fine-tuning updates all weights within the network but requires immense computational power.
        To mitigate this, developers use Parameter-Efficient Fine-Tuning (PEFT) techniques like LoRA (Low-Rank Adaptation), which freeze the original model weights and inject small, trainable rank-decomposition matrices into the network layers, dramatically reducing training costs and hardware requirements.
        """,
        
        """
        Text Splitting and Chunking Strategies

        Chunking is the foundational data-preparation process in RAG where long documents are broken down into smaller, distinct segments of text before embedding. If chunks are too large, the embedding vector becomes diluted with multiple topics, causing the retrieval system to lose precision.
        If chunks are too small, critical context is severed, leaving the LLM with incomplete information. Striking a balance is vital for the semantic search engine to pinpoint the right data.
        Common chunking strategies range from fixed-size text splitting to semantic chunking. Fixed-size chunking splits text based on a strict character or token count, often utilizing a "chunk overlap" buffer (e.g., 50 tokens) to ensure that context spanning across boundaries isn't lost.
        Advanced semantic chunking uses natural language processing to identify sentence boundaries, paragraph breaks, or changes in semantic drift, dividing the text only when the underlying topic actually shifts.
        """,
        
        """
        Evaluation of RAG Systems (RAGAS)

        Evaluating the performance of a RAG pipeline is complex because it requires measuring both the quality of the retrieved context and the quality of the generated response. Traditional NLP metrics like BLEU or ROUGE are insufficient because they look for exact word matches rather than factual correctness or semantic alignment.
        Modern evaluation frameworks, such as RAGAS (Retrieval Augmented Generation Assessment), rely on LLMs acting as judges to systematically score the pipeline.
        The evaluation process is broken into core metrics: faithfulness, answer relevance, and context precision. Faithfulness measures whether the LLM's final answer is strictly grounded in the retrieved context, capturing potential hallucinations.
        Answer relevance assesses how well the generated response directly answers the user's question. Context precision and context recall evaluate the retrieval engine itself, ensuring that the vector database returned all the necessary information and minimized irrelevant data.
        """,
        
        """
        Prompt Engineering and Prompt Templates

        Prompt engineering is the empirical discipline of structuring, formatting, and refining input text to effectively guide the behavior and output of a Large Language Model. Because LLMs are highly sensitive to context, minor adjustments in instructions, constraints, or formatting can drastically alter the quality of the response.
        Prompt engineering establishes the operational guardrails, tone, persona, and logical reasoning pathways for an AI application.
        Prompt templates are reusable, dynamic prompt structures that contain placeholders for variables like user queries, chat history, and retrieved context. In production RAG systems, developers use frameworks like LangChain to programmatically assemble prompts on the fly.
        Advanced prompting strategies include Few-Shot Prompting, which provides the model with exemplary input-output pairs to demonstrate a task, and Chain-of-Thought (CoT) prompting, which explicitly instructs the model to break down its reasoning step-by-step before delivering a final answer.
        """,
        
        """
        Advanced Retrieval: Re-ranking and Query Expansion

        Basic vector retrieval often struggles with complex queries or ambiguous phrasing because it relies entirely on a single mathematical distance calculation. To overcome this limitation, advanced RAG architectures implement Query Expansion techniques.
        Query expansion uses an LLM to take a user's short input and generate multiple variations, sub-questions, or hypothetical documents (Hypothetical Document Embeddings or HyDE), broadening the net cast into the vector store to catch all relevant documents.
        Once a broad set of documents is retrieved, the system applies a two-stage retrieval process using a Re-ranker. While vector databases are excellent at scanning millions of documents quickly to find the top 50 matches, they lack fine-grained semantic comprehension.
        A Cross-Encoder re-ranking model is then introduced to evaluate the exact user query against those 50 retrieved documents simultaneously, re-ordering them so that the absolute most contextually rich fragments are placed at the very top for the LLM to read.
        """,
        
        """
        LangChain and LangChain Expression Language (LCEL)

        LangChain is an open-source development framework designed to simplify the construction of applications powered by large language models. Foundational LLM applications require chaining together multiple disparate components, including data loaders, vector stores, prompt formatting, model calls, and output parsers.
        LangChain provides modular abstractions and standardized interfaces for these components, allowing developers to build robust AI workflows without reinventing the wheel.
        LangChain Expression Language (LCEL) is a declarative syntax provided by the framework to easily compose chains from individual components. Utilizing the Linux pipe operator (|), LCEL allows developers to stream data sequentially from one runnable object to the next with minimal boilerplate code.
        Under the hood, LCEL automatically provides built-in support for parallel execution, asynchronous streaming, intermediate state inspection, and fallback handling, making production deployment highly efficient.
        """,
        
        """
        Agents and Tool Use (Function Calling)

        AI Agents represent a paradigm shift from rigid, sequential chains to dynamic, autonomous systems driven by LLMs. An agent uses an LLM as a central reasoning engine to evaluate user intent, formulate an execution plan, and dynamically choose which actions to take.
        Instead of simply generating a text response, the agent can stop, call external tools, analyze the tool's output, and loop through this cycle until it successfully solves the prompt.
        Tool use, often referred to as function calling, is the mechanism that gives language models hands to interact with the digital world. By providing the LLM with structured JSON descriptions of external APIs, databases, or python scripts, the model can explicitly output an execution request (like generating a SQL query or a web search parameter) rather than conversational text.
        This allows agents to fetch real-time weather information, query corporate databases, calculate complex math, or execute code securely.
        """,
        
        """
        Multi-Modal AI and Multimodal RAG

        Multi-Modal AI refers to artificial intelligence models capable of processing, understanding, and generating multiple distinct types of data modalities, such as text, images, audio, and video, simultaneously. Early AI systems were strictly single-modality text or image networks.
        Modern multi-modal models utilize a shared embedding space where visual tokens and linguistic tokens are mapped together, enabling a model to look at a chart or a diagram and reason about it using natural language text.
        Multimodal RAG extends the standard retrieval architecture to incorporate unstructured visual data alongside text repositories. In a multimodal RAG setup, document loaders utilize OCR (Optical Character Recognition) and vision models to parse PDFs containing complex tables, infographics, and images.
        These visual elements are either converted into detailed textual summaries or embedded directly using multimodal models like CLIP, allowing a user to query a database and retrieve not just matching paragraphs, but the exact relevant diagrams and images.
        """
    ]

    # Check if directory exists; if not, create it
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
        print(f"[INFO] Directory '{data_dir}' created successfully.")
    else:
        print(f"[INFO] Directory '{data_dir}' already exists. Files will be overwritten/updated.")

    # Iterate and write content to separate text files
    for i, content in enumerate(sample_docs_content):
        file_name = f"doc_{i}.txt"
        file_path = os.path.join(data_dir, file_name)
        
        try:
            with open(file_path, "w", encoding='utf-8') as f:
                # Use strip() to remove unnecessary leading/trailing blank lines in the files
                f.write(content.strip())
            print(f"  -> Created: {file_name}")
        except IOError as e:
            print(f"[ERROR] Failed to write file {file_name}. Reason: {e}", file=sys.stderr)

    print(f"\n[SUCCESS] Sample documents created in: {os.path.abspath(data_dir)}")


def main():
    # Define target directory name
    DATA_DIR = "data"
    
    print("Starting document creation script...")
    print("-" * 50)
    
    create_sample_documents(DATA_DIR)
    
    print("-" * 50)
    print("Process finished successfully!")


if __name__ == "__main__":
    main()