"""
================================================================================
📌 SCRIPT PURPOSE: Implementing and Evaluating LangGraph Streaming Configurations
================================================================================
This script builds a stateful chatbot ("SuperBot") utilizing LangGraph and 
Groq's Qwen model. It showcases how to leverage a MemorySaver checkpointer 
to maintain cross-turn thread conversations, alongside deep-dive comparisons of:
  
  1. Synchronous vs. Asynchronous execution engines (.stream() vs. .astream_events())
  2. State Streaming Modes:
     - stream_mode="updates" : Yields only the incremental changes generated by a node.
     - stream_mode="values"  : Yields the completely compiled global state array.
================================================================================
"""

import os
import logging
import warnings
from typing import Annotated
from typing_extensions import TypedDict
from dotenv import load_dotenv

# LangChain & Model Provider Utilities
from langchain_groq import ChatGroq
from langchain_core.messages import AnyMessage, HumanMessage

# LangGraph Core Framework Utilities
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver

# Suppress heavy console warning logs
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)

# ==============================================================================
# 1. INITIALIZATION: Environment & Keys Setup
# ==============================================================================
load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY")

# ==============================================================================
# 2. DEFINING THE REDUCER STATE SCHEMA & BOT LOGIC
# ==============================================================================
class State(TypedDict):
    # Annotated + add_messages appends turns automatically instead of overriding state keys
    messages: Annotated[list[AnyMessage], add_messages]

# Hook up our high-performance open-weight target inference engine
LLM_MODEL = "qwen/qwen3-32b"
llm_groq = ChatGroq(model=LLM_MODEL)

def superbot(state: State):
    """The central inference node passing active conversational history to the LLM"""
    return {"messages": [llm_groq.invoke(state['messages'])]}

# ==============================================================================
# 3. COMPILING GRAPH STATE MACHINE WITH MEMORY
# ==============================================================================
# Instantiating the in-memory checkpointer provider for conversation multi-turn tracking
memory = MemorySaver()

# Build the Graph canvas structure
graph = StateGraph(State)
graph.add_node("SuperBot", superbot)
graph.add_edge(START, "SuperBot")
graph.add_edge("SuperBot", END)

# Compile into an executable application, registering our short-term persistent memory
graph_builder = graph.compile(checkpointer=memory)

# Render and save pipeline diagram locally on execution
OUTPUT_IMAGE_PATH = "Image_PNGs/Streaming.png"
graph_builder.get_graph().draw_mermaid_png(output_file_path=OUTPUT_IMAGE_PATH)    
os.system(f"open {OUTPUT_IMAGE_PATH}")

# ==============================================================================
# 4. SYNCHRONOUS STREAMING UTILITIES (.stream())
# ==============================================================================
print("======================================================================")
print("🔥 PART 1: EVALUATING SYNCHRONOUS (.stream()) CHANNELS")
print("======================================================================")

# Establish a continuous thread block reference configuration 
config_thread_1 = {"configurable": {"thread_id": "111"}}

# ------------------------------------------------------------------------------
# 💡 KNOWLEDGE CORNER: stream_mode="updates"
# What it does: This prints out ONLY what changes inside a node function. 
# It yields an isolated dictionary snippet matching the exact return block 
# of the specific Node that just finished execution, keeping the network output clean.
# ------------------------------------------------------------------------------
print("\n🔹 Action A: Executing stream_mode='updates'")
print("----------------------------------------------------------------------")
query_1 = "Hi, My name is Ash and I like to hike."
for chunk in graph_builder.stream({'messages': [HumanMessage(content=query_1)]}, config_thread_1, stream_mode="updates"):
    print("Received Update Yield Chunk:")
    print(chunk)

# ------------------------------------------------------------------------------
# 💡 KNOWLEDGE CORNER: stream_mode="values"
# What it does: Instead of an isolated update dictionary, this yields the 
# completely compiled state history array of the entire graph up to that millisecond. 
# You will see the entire accumulated message chain listed recursively.
# ------------------------------------------------------------------------------
print("\n🔹 Action B: Executing stream_mode='values'")
print("----------------------------------------------------------------------")
query_2 = "I also like soccer."
for chunk in graph_builder.stream({'messages': [HumanMessage(content=query_2)]}, config_thread_1, stream_mode="values"):
    print("Received Compiled Values Yield Chunk:")
    print(chunk)

print("\n🔹 Action C: Executing another stream_mode='updates' sequence on the same thread")
print("----------------------------------------------------------------------")
query_3 = "I also like pickleball."
for chunk in graph_builder.stream({'messages': [HumanMessage(content=query_3)]}, config_thread_1, stream_mode="updates"):
    print("Received Update Yield Chunk:")
    print(chunk)


# ==============================================================================
# 5. ASYNCHRONOUS EVENT-DRIVEN STREAMING (.astream_events())
# ==============================================================================
# Define an asynchronous orchestration function wrapper for executing event loops
async def run_async_streaming_demo():
    print("\n======================================================================")
    print("🔥 PART 2: EVALUATING ASYNCHRONOUS (.astream_events()) PIPELINES")
    print("======================================================================")
    
    # --------------------------------------------------------------------------
    # 💡 KNOWLEDGE CORNER: .stream() vs .astream_events()
    # 
    # - .stream(): A synchronous iterator. It pauses the Python process block 
    #   and waits for entire processing nodes to completely finish before yielding.
    # 
    # - .astream_events(version="v2"): An asynchronous, multi-threaded event loop engine.
    #   It streams back real-time architectural engine diagnostics (on_chat_model_stream,
    #   on_node_start, on_chain_end, etc.), allowing you to stream raw tokens from the LLM 
    #   incrementally right to the client console while the node is still processing!
    # --------------------------------------------------------------------------
    
    config_thread_2 = {"configurable": {"thread_id": "2222"}}
    async_query = "Hi My name is Ash and I like to play soccer"
    
    print(f"Opening event hook connection for query: '{async_query}'\n")
    
    async for event in graph_builder.astream_events({"messages": [HumanMessage(content=async_query)]}, config_thread_2, version="v2"):
        # Extract metadata identifiers for target rendering filter
        kind = event["event"]
        name = event["name"]
        
        # Filter 1: Catch when the LangGraph orchestration engine runs individual nodes
        if kind == "on_chain_start" and name == "SuperBot":
            print(f"🎬 Graph Engine Event -> Node Processing Initialized: '{name}'")
            
        # Filter 2: Intercept raw chat tokens mid-flight as the LLM generates them
        elif kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                print(content, end="|", flush=True)
                
        # Filter 3: Catch when nodes finalize data execution
        elif kind == "on_chain_end" and name == "SuperBot":
            print(f"\n🛑 Graph Engine Event -> Node Processing Concluded: '{name}'")

# Execute our non-blocking asynchronous event evaluation loop
if __name__ == "__main__":
    import asyncio
    asyncio.run(run_async_streaming_demo())